name: publish release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Create new buildx builder
        run: docker buildx create --name custom_builder --use

      - name: Build images
        run: docker buildx build --platform=linux/amd64 --platform=linux/arm64 -t bolzerdev/peppol-bis-billing-validator:${{github.ref_name}} -t bolzerdev/peppol-bis-billing-validator:latest  . --push
